### ISSUE TITLE
Broken walkthrough

### ISSUE THREAD

**Issue by bucknerns** [uber/Cadence-Docs#171]
https://github.com/uber/Cadence-Docs/blob/master/src/docs/01-get-started/01-server-installation.md
All the docker containers don't start because prometheus.yml should be pulled under a prometheus folder and the graphana config folder is not pulled.

**Comment by ibarrajo** [comment]
Hi, I just tested and could not replicate.

Got the docker-compose.yml and prometheus.yml:
```
curl -O https://raw.githubusercontent.com/uber/cadence/master/docker/docker-compose.yml && curl -O https://raw.githubusercontent.com/uber/cadence/master/docker/prometheus/prometheus.yml
```

And ran them successfully with `docker-compose up`

Are you still running into this issue?

**Comment by bucknerns** [comment]
It is working now. Looks like it was a bug in the in the master-auto-setup docker image and can be reproduced using ubercadence/server:v1.2.6-auto-setup.

**Comment by Akshit8** [comment]
Hi, I think this issue still persists. So running the curl command mentioned in the docs

```sh
curl -O https://raw.githubusercontent.com/cadence-workflow/cadence/master/docker/docker-compose.yml && curl -O https://raw.githubusercontent.com/cadence-workflow/cadence/master/docker/prometheus/prometheus.yml
```
This only downloads `docker-compose.yml` and `promethues.yml` 

```
.
├── docker-compose.yml
└── prometheus.yml
```

But inside `docker-compose.yml` it clearly has these volumes under promethues and grafana service. Prometheus looks for `prometheus.yml` inside promethues directory and Grafana looks for `grafana.ini` inside grafana directory. Both of these are not downloaded with above curl command.

```yml
...
prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
....
grafana:
    image: grafana/grafana
    volumes:
      - ./grafana:/etc/grafana
    user: "1000"
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
```
